### ISSUE TITLE
Disable all tracking if db version is incompatible with current version

### ISSUE THREAD

**Issue by shadyvb** [wp-stream/stream#422]
- [ ] Stop any logging operations if database version is not current.
- [ ] Alter db update notice to notify user that Stream tracking is disabled till db is upgraded
- [ ] Make sure extensions are disabled as well

Edit: Primary reason for that is that the site will not be working correctly with Stream outputting errors while trying to track anything, like user login for example.

/cc @fjarrett
